services:
  web:
    build: .
    expose:
      - "8000"  # Gunicorn будет слушать на 8000 порту внутри контейнера
    environment:
      - DJANGO_ENV=production
    networks:
      - localnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Nginx будет слушать на порту 80 (внешний порт сервера)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - localnet

networks:
  localnet:
    driver: bridge