 
services:
  web:
    build: .
    expose:
      - "8002"  
      - .:/app
    environment:
      - DJANGO_ENV=production
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles 
    networks:
      - localnet

  nginx:
    image: nginx:latest
    ports:
      - "8002:80"   
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web
    networks:
      - localnet
networks:
  localnet:
    driver: bridge
