# Generated by Django 5.1.1 on 2024-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_menu_remove_menuitem_menu_name_alter_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
